import { describe, expect, it } from 'vitest';
import { buildAutomaticRoutingTemplate, markAutoGeneratedRulesAsManual, resolveAutoRoutingPersonaRole } from './agent-routing-template';

describe('resolveAutoRoutingPersonaRole', () => {
  it('falls back to the base persona slug for custom personas', () => {
    expect(resolveAutoRoutingPersonaRole({ slug: 'custom-reviewer', basePersonaSlug: 'qa' })).toBe('qa');
    expect(resolveAutoRoutingPersonaRole({ slug: 'developer', basePersonaSlug: null })).toBe('developer');
    expect(resolveAutoRoutingPersonaRole({ slug: 'custom', basePersonaSlug: null })).toBe('unknown');
  });
});

describe('buildAutomaticRoutingTemplate', () => {
  it('creates PO and Dev auto-routing rules for requirement and task lanes', () => {
    const result = buildAutomaticRoutingTemplate({
      agents: [
        { agentId: 'agent-po', agentName: 'Ortega', role: 'product-owner', personaId: 'persona-po', deploymentId: 'deployment-po' },
        { agentId: 'agent-dev', agentName: 'Didi', role: 'developer', personaId: 'persona-dev', deploymentId: 'deployment-dev' },
      ],
    });

    expect(result).toEqual({
      templateId: 'po-dev',
      existingRuleCount: 0,
      requiresOverwriteConfirmation: false,
      rules: [
        expect.objectContaining({
          agent_id: 'agent-po',
          priority: 10,
          conditions: { memo_type: ['requirement', 'user_story'] },
          action: { auto_reply_mode: 'process_and_report', forward_to_agent_id: null },
          metadata: expect.objectContaining({ auto_generated: true, template_id: 'po-dev' }),
        }),
        expect.objectContaining({
          agent_id: 'agent-dev',
          priority: 20,
          conditions: { memo_type: ['task', 'dev_task'] },
          action: { auto_reply_mode: 'process_and_report', forward_to_agent_id: null },
          metadata: expect.objectContaining({ auto_generated: true, template_id: 'po-dev' }),
        }),
      ],
    });
  });

  it('adds QA review routing and overwrite protection when rules already exist', () => {
    const result = buildAutomaticRoutingTemplate({
      agents: [
        { agentId: 'agent-po', agentName: 'Ortega', role: 'product-owner' },
        { agentId: 'agent-dev', agentName: 'Didi', role: 'developer' },
        { agentId: 'agent-qa', agentName: 'Qasim', role: 'qa' },
      ],
      existingRuleCount: 2,
    });

    expect(result.templateId).toBe('po-dev-qa');
    expect(result.requiresOverwriteConfirmation).toBe(true);
    expect(result.existingRuleCount).toBe(2);
    expect(result.rules).toHaveLength(3);
    expect(result.rules[2]).toEqual(expect.objectContaining({
      agent_id: 'agent-qa',
      priority: 30,
      conditions: { memo_type: ['review'] },
      metadata: expect.objectContaining({ auto_generated: true, template_id: 'po-dev-qa' }),
    }));
  });

  it('keeps solo dev deployments on single-agent handling without auto rules', () => {
    const result = buildAutomaticRoutingTemplate({
      agents: [{ agentId: 'agent-dev', agentName: 'Didi', role: 'developer' }],
      existingRuleCount: 4,
    });

    expect(result).toEqual({
      templateId: 'solo-dev',
      rules: [],
      requiresOverwriteConfirmation: false,
      existingRuleCount: 4,
    });
  });
});

describe('markAutoGeneratedRulesAsManual', () => {
  it('flips auto_generated metadata to false when a generated rule is manually edited', () => {
    const result = markAutoGeneratedRulesAsManual([
      {
        id: 'rule-1',
        metadata: {
          auto_generated: true,
          template_id: 'po-dev',
        },
      },
      {
        id: 'rule-2',
        metadata: {
          auto_generated: false,
        },
      },
    ]);

    expect(result).toEqual([
      {
        id: 'rule-1',
        metadata: {
          auto_generated: false,
          template_id: 'po-dev',
        },
      },
      {
        id: 'rule-2',
        metadata: {
          auto_generated: false,
        },
      },
    ]);
  });
});
