import type { RoutingAutoReplyMode } from './agent-routing-rule';

export type AutoRoutingPersonaRole = 'product-owner' | 'developer' | 'qa' | 'unknown';
export type AutoRoutingTemplateId = 'none' | 'solo-dev' | 'po-dev' | 'po-dev-qa';

export interface AutoRoutingTemplateAgent {
  agentId: string;
  agentName: string;
  role: AutoRoutingPersonaRole;
  personaId?: string | null;
  deploymentId?: string | null;
}

export interface AutoRoutingTemplateMetadata {
  auto_generated: boolean;
  template_id: Exclude<AutoRoutingTemplateId, 'none'>;
  generated_from_roles: AutoRoutingPersonaRole[];
}

export interface AutoRoutingRuleDraft {
  agent_id: string;
  persona_id: string | null;
  deployment_id: string | null;
  name: string;
  priority: number;
  match_type: 'event';
  conditions: { memo_type: string[] };
  action: { auto_reply_mode: RoutingAutoReplyMode; forward_to_agent_id: null };
  target_runtime: 'openclaw';
  target_model: null;
  is_enabled: true;
  metadata: AutoRoutingTemplateMetadata;
}

export interface AutoRoutingTemplateResult {
  templateId: AutoRoutingTemplateId;
  rules: AutoRoutingRuleDraft[];
  requiresOverwriteConfirmation: boolean;
  existingRuleCount: number;
}

const DEFAULT_ACTION: AutoRoutingRuleDraft['action'] = {
  auto_reply_mode: 'process_and_report',
  forward_to_agent_id: null,
};

export function resolveAutoRoutingPersonaRole(input: {
  slug?: string | null;
  basePersonaSlug?: string | null;
}): AutoRoutingPersonaRole {
  const value = (input.basePersonaSlug ?? input.slug ?? '').trim().toLowerCase();
  if (value === 'product-owner') return 'product-owner';
  if (value === 'developer') return 'developer';
  if (value === 'qa') return 'qa';
  return 'unknown';
}

function dedupeAgents(agents: AutoRoutingTemplateAgent[]) {
  const seen = new Set<string>();
  return agents.filter((agent) => {
    if (!agent.agentId || seen.has(agent.agentId)) return false;
    seen.add(agent.agentId);
    return true;
  });
}

function createRuleDraft(
  agent: AutoRoutingTemplateAgent,
  memoTypes: string[],
  priority: number,
  templateId: Exclude<AutoRoutingTemplateId, 'none'>,
  generatedFromRoles: AutoRoutingPersonaRole[],
): AutoRoutingRuleDraft {
  return {
    agent_id: agent.agentId,
    persona_id: agent.personaId ?? null,
    deployment_id: agent.deploymentId ?? null,
    name: `${agent.agentName} auto route ${memoTypes.join('/')}`,
    priority,
    match_type: 'event',
    conditions: { memo_type: memoTypes },
    action: { ...DEFAULT_ACTION },
    target_runtime: 'openclaw',
    target_model: null,
    is_enabled: true,
    metadata: {
      auto_generated: true,
      template_id: templateId,
      generated_from_roles: generatedFromRoles,
    },
  };
}

export function buildAutomaticRoutingTemplate(input: {
  agents: AutoRoutingTemplateAgent[];
  existingRuleCount?: number;
}): AutoRoutingTemplateResult {
  const agents = dedupeAgents(input.agents);
  const existingRuleCount = Math.max(0, input.existingRuleCount ?? 0);
  const productOwner = agents.find((agent) => agent.role === 'product-owner');
  const developer = agents.find((agent) => agent.role === 'developer');
  const qa = agents.find((agent) => agent.role === 'qa');

  if (agents.length <= 1 && developer) {
    return {
      templateId: 'solo-dev',
      rules: [],
      requiresOverwriteConfirmation: false,
      existingRuleCount,
    };
  }

  if (!productOwner || !developer) {
    return {
      templateId: 'none',
      rules: [],
      requiresOverwriteConfirmation: false,
      existingRuleCount,
    };
  }

  const templateId: Exclude<AutoRoutingTemplateId, 'none' | 'solo-dev'> = qa ? 'po-dev-qa' : 'po-dev';
  const generatedFromRoles = qa ? ['product-owner', 'developer', 'qa'] as AutoRoutingPersonaRole[] : ['product-owner', 'developer'] as AutoRoutingPersonaRole[];
  const rules: AutoRoutingRuleDraft[] = [
    createRuleDraft(productOwner, ['requirement', 'user_story'], 10, templateId, generatedFromRoles),
    createRuleDraft(developer, ['task', 'dev_task'], 20, templateId, generatedFromRoles),
  ];

  if (qa) {
    rules.push(createRuleDraft(qa, ['review'], 30, templateId, generatedFromRoles));
  }

  return {
    templateId,
    rules,
    requiresOverwriteConfirmation: existingRuleCount > 0,
    existingRuleCount,
  };
}

export function markAutoGeneratedRulesAsManual<T extends { metadata?: Record<string, unknown> | null }>(rules: T[]): T[] {
  return rules.map((rule) => {
    const metadata = rule.metadata && typeof rule.metadata === 'object' && !Array.isArray(rule.metadata)
      ? { ...rule.metadata }
      : {};

    if (metadata.auto_generated !== true) {
      return rule;
    }

    return {
      ...rule,
      metadata: {
        ...metadata,
        auto_generated: false,
      },
    };
  });
}
